modLoader = "javafml"
loaderVersion = "[52,)"
license = "MIT"
issueTrackerURL = "https://github.com/kara/UUIDBridge/issues"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
description = '''${modDescription}'''

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},${minecraftVersionUpper})"
ordering = "NONE"
side = "BOTH"
